### ISSUE TITLE
amtm 3.2.0 Module format_disk.mod download failed

### ISSUE THREAD

**Issue by creisey** [decoderman/amtm#12]
I have a merlin router with FW-380.70 and used amtm and diversion a couple of years and it worked great. but now with the last update i cant update anymore and a reinstall failed comletely:

i can ping diversion.ch form my router so that shouldnt be the problem.

**Comment by decoderman** [comment]
You are using a very outdated and insecure firmware on this router. That model is no longer in the supported Asuswrt-Merlin model list and will no longer be updated.
Due to the expiration of the built in Root CA certificates that this firmware comes with, the curl command cannot securely complete the required commands.

There is a [discussion here with a workaround](https://www.snbforums.com/threads/ac87u-all-download-attempts-failed.75049/) to run the curl command in insecure mode.

**Comment by creisey** [comment]
thx for the answer, i have changed to a RT-AC68U with the latest firmware and all things are woring great

**Comment by mernamer** [comment]
Wanted to add, because had the same issue with RT-AC68U running Merlin 384.5:
The workaround @decoderman shared above worked.

Planning to update ASAP, for the normal reasons plus to see if that resolves the issue too, but will update if I find anything relevant.
