### ISSUE TITLE
How to install entware on jffs

### ISSUE THREAD

**Issue by Cryolitia** [decoderman/amtm#29]
I have been informed of all the risks of this action and am willing to bear all the consequences. I bought multiple ASUS routers to ensure that the damage to a single router is not a big deal.

I don't want to plugin any USB devices at all.

I have read the post https://www.snbforums.com/threads/how-to-install-entware-to-jffs-without-usb-flashdrive.39700/ but it seems outdate.

**Comment by decoderman** [comment]
Warning: I DO NOT recommend installing Entware to /jffs as it will wear out the only persistent storage on your router much faster. Additionally there's the chance that the jffs partition will run out of space.

With that warning out of the way, follow these instructions carefully to install Entware to /jffs:
1. Enter `amtm` into an SSH terminal of your Asuswrt-Merlin router.
2. If amtm has never been run before, select theme and let it do its thing until it finishes.
3. Enter `ep` into amtm, it will show that this will install Entware. DO NOT continue or Exit from amtm as this will delete the file /jffs/addons/amtm/entware_setup.mod automatically.
4. Instead, Use `CTRL-C` to force quit amtm.
5. Modify /jffs/addons/amtm/entware_setup.mod thus:
- Edit variable `minsize=71680` on line 31 to something lower, like `minsize=15360`. That would be 15MB in KB.
- Edit all three `PART_TYPES` variables beginning on line 61 up to 77 to include the /jffs partition by adding `|jffs2` after, like so for the mips line: `PART_TYPES='ext2|ext3|jffs'`
6. Open amtm again and enter `ep` and continue with installing Entware, selecting the jffs partition that now shows up.
7. Let it finish installing Entware.
8. Create file `/jffs/scripts/services-start` and insert the following so that Entware is mounted when booting/rebooting the router: 
`#!/bin/sh`
`. /jffs/addons/amtm/mount-entware.mod /jffs # Added by amtm`
9. Make the file executable: `chmod a+rx /jffs/scripts/services-start`
10. Theoretically, you could delete the file /jffs/scripts/services-start/post-mount that the Entware installer created. But it will be auto re-created if you ever update amtm. So just leave it there as it will never run without a USB device attached to your router. And even then it will do nothing as it would not find an Entware installation on the attached device.
11. All done. Reboot your router to test if Entware will mount to /opt. 

The file /jffs/addons/amtm/entware_setup.mod will automatically delete itself during the Entware installation, so keep it handy after you've done the modifications listed above.
You can safely check for and update amtm or Entware through amtm with `u` after Entware installation.

**Comment by Cryolitia** [comment]
Thanks for your reply, I really appreciate your patience. It works for me.
