### ISSUE TITLE
Reboot scheduler - grep: /jffs/scripts/post-mount: No such file or directory

### ISSUE THREAD

**Issue by francoism90** [decoderman/amtm#5]
This keeps showing on a clean (bridged) ASUS RT-AC78U 384.11.
Is this fatal for the reboot scheduler? I don't have any other tools installed (as this is used as bridge).

Thanks! If more info is needed, please let me know.

**Comment by decoderman** [comment]
The reboot scheduler uses init-start to write the cron job, so that error is unrelated to that.
You may get this error because you have a stale swap file on your USB device (likely myswap.swp).
This error is fixed and will be available with the next release.

Of interest to me would be the contents of /jffs/scripts/ to determine why exactly you get the post-mount error.
