### ISSUE TITLE
unterminated quoted string

### ISSUE THREAD

**Issue by chavyleung** [decoderman/amtm#6]
```bash
admin@RT-AC86U:/jffs/scripts# /usr/sbin/curl -Os https://raw.githubusercontent.com/decoderman/amtm/master/amtm && sh amtm
Terminated
admin@RT-AC86U:/jffs/scripts# ./amtm 
-sh: ./amtm: Permission denied
admin@RT-AC86U:/jffs/scripts# chmod 755 amtm 
admin@RT-AC86U:/jffs/scripts# ./amtm 
./amtm: line 2454: syntax error: unterminated quoted string
```

**Comment by decoderman** [comment]
The amtm code is error free and unchanged since the last release on June 21. There's something wrong on your end. 
Try to run the install command again, making sure you are running this on a supported router (which the RT-AC86U is) with supported firmware. Diversion requirements also apply to amtm, for obvious reasons.
https://diversion.ch/diversion/requirements.html

**Comment by chavyleung** [comment]
Resolved, Fuxk GFW!
